/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/4D FLORAL.gltf");
  return (
    <group {...props} dispose={null}>
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["da"].geometry}
        material={materials["A"]}
      />
            <mesh
        castShadow
        receiveShadow
        geometry={nodes["da_1"].geometry}
        material={materials["B"]}
      />
            <mesh
        castShadow
        receiveShadow
        geometry={nodes["da_2"].geometry}
        material={materials["C"]}
      />
    </group>
  );
}

useGLTF.preload("/4D FLORAL.gltf");